"""criacao_real_das_tabelas

Revision ID: 7bd45697e6e4
Revises: cbcd1bc0316e
Create Date: 2026-05-26 22:07:19.939143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bd45697e6e4'
down_revision: Union[str, Sequence[str], None] = 'cbcd1bc0316e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
